<?php
echo "\n";
echo "<!DOCTYPE html>\n";
echo "<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"ja\" prefix=\"og: http://ogp.me/ns#\">\n";
echo "<head profile=\"http://gmpg.org/xfn/11\">\n";
echo "<link rel=\"master\" type=\"text/css\" href=\"master.css\">\n";
echo "<!-- title いる？ -->\n";
echo "<title>岐阜県可児市御嵩町にあるコインランドリーレインボーです。ラスパ御嵩から徒歩５分程度</title>\n";
echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n";
echo "<meta name=\"viewport\" content=\"width=device-width, user-scalable=no\">\n";
echo "<meta http-equiv=\"content-style-type\" content=\"text/css\" />\n";
echo "<meta http-equiv=\"content-script-type\" content=\"text/javascript\" />\n";
echo "<meta charset=\"utf-8\">\n";
echo "\n";
echo "<link rel=\"stylesheet\" href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css\">\n";
echo "\n";
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap.css\">\n";
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"default.css\">\n";
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"breadcrumb.css\">\n";
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"form.css\">\n";
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"master.css\">\n";
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"vegas.min.css\">\n";
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"original.css\">\n";
echo "\n";
echo "\n";
echo "<!-- This site is optimized with the Yoast SEO plugin v3.0.4 - https://yoast.com/wordpress/plugins/seo/ -->\n";
echo "<meta name=\"description\" content=\"岐阜県可児市御嵩町1146-2にあるコインランドリーレインボーです。ラスパ御嵩から徒歩５分程度。お湯で洗濯できます。\"/>\n";
echo "<meta name=\"robots\" content=\"noodp\"/>\n";
echo "<!-- meta name Webサイトの概要をまとめたテキストの内容を指示する、検索エンジンの検索結果画面に示される。-->\n";
echo "<!-- meta name=”robots”>とは、HTMLの<head>タグ内に記載するメタタグの一種です。メタタグとは、メタ要素とも呼ばれ、Webページの情報を検索エンジンやブラウザにインデックスすることを拒否したり、キャッシュを拒否したりと、クローラーの動作を制御する役割を果たします。<head>タグ内に記載されるので、サイトを訪問するユーザーからは直接見えることはありません。-->\n";
echo "<link rel=\"canonical\" href=\"https://toshipy.github.io/coinlaundry/\" />\n";
echo "<!-- SEO内部対策のひとつ「インデックス最適化」の基本となるcanonical属性タグを利用した「URL正規化」をする必要があります。\n";
echo "このURLの正規化処理をしていない場合、せっかく良いコンテンツを作成しても複数の異なるURLで同一のページを閲覧できる状態となってしまうことがあり、場合によっては重複コンテンツとみなされてマイナスの評価を受ける可能性があります。-->\n";
echo "<link rel=\"next\" href=\"https://toshipy.github.io/coinlaundry//2/\" />\n";
echo "\n";
echo "<meta property=\"og:locale\" content=\"ja_JP\" />\n";
echo "<!-- 本エントリーでお伝えしたいのはこの部分で、日本語しかサポートしていない場合は次のように「ja_JP」を設定したmeta要素を追加すると良いでしょう。-->\n";
echo "<meta property=\"og:type\" content=\"website\" />\n";
echo "<!--TOPページの場合は「website」、WEBサイト上の記事ページなど、TOPページ以外には「article」を指定します。-->\n";
echo "<meta property=\"og:title\" content=\"御嵩町のコインランドリーレインボー\" />\n";
echo "<meta property=\"og:description\" content=\"岐阜県可児市御嵩町にあるコインランドリーレインボーです。ラスパ御嵩から徒歩５分程度。お湯で洗濯できます。\" />\n";
echo "<meta property=\"og:url\" content=\"https://toshipy.github.io/coinlaundry/\" />\n";
echo "<meta property=\"og:site_name\" content=\"ラポール\" />\n";
echo "<meta name=\"twitter:card\" content=\"summary\"/>\n";
echo "<meta name=\"twitter:description\" content=\"岐阜県可児市御嵩町にあるコインランドリーレインボーです。ラスパ御嵩から徒歩５分程度。お湯で洗濯できます。\"/>\n";
echo "<meta name=\"twitter:title\" content=\"御嵩町のコインランドリーレインボー\"/>\n";
echo "<!--この記述はよくわからん<script type='application/ld+json'>{\"@context\":\"http:\/\/schema.org\",\"@type\":\"WebSite\",\"url\":\"http:\/\/coinlaundry-rapport.com\/\",\"name\":\"\u30e9\u30dd\u30fc\u30eb\",\"potentialAction\":{\"@type\":\"SearchAction\",\"target\":\"http:\/\/coinlaundry-rapport.com\/?s={search_term_string}\",\"query-input\":\"required name=search_term_string\"}}</script>-->\n";
echo "<!-- / Yoast SEO plugin. -->\n";
echo "\n";
echo "		<script type=\"text/javascript\">\n";
echo "			window._wpemojiSettings = {\"baseUrl\":\"http:\/\/s.w.org\/images\/core\/emoji\/72x72\/\",\"ext\":\".png\",\"source\":{\"concatemoji\":\"http:\/\/coinlaundry-rapport.com\/wp-includes\/js\/wp-emoji-release.min.js?ver=4.3.23\"}};\n";
echo "		</script>\n";
echo "		<style type=\"text/css\">\n";
echo "img.wp-smiley,\n";
echo "img.emoji {\n";
echo "	display: inline !important;\n";
echo "	border: none !important;\n";
echo "	box-shadow: none !important;\n";
echo "	height: 1em !important;\n";
echo "	width: 1em !important;\n";
echo "	margin: 0 .07em !important;\n";
echo "	vertical-align: -0.1em !important;\n";
echo "	background: none !important;\n";
echo "	padding: 0 !important;\n";
echo "}\n";
echo "</style>\n";
echo "<link rel='stylesheet' id='wp-pagenavi-css'  href='http://coinlaundry-rapport.com/wp-content/plugins/wp-pagenavi/pagenavi-css.css?ver=2.70' type='text/css' media='all' />\n";
echo "<!-- This site uses the Google Analytics by Yoast plugin v5.4.6 - Universal enabled - https://yoast.com/wordpress/plugins/google-analytics/ -->\n";
echo "<script type=\"text/javascript\">\n";
echo "	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n";
echo "		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n";
echo "		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n";
echo "	})(window,document,'script','//www.google-analytics.com/analytics.js','__gaTracker');\n";
echo "\n";
echo "	__gaTracker('create', 'UA-70787907-1', 'auto');\n";
echo "	__gaTracker('set', 'forceSSL', true);\n";
echo "	__gaTracker('send','pageview');\n";
echo "\n";
echo "</script>\n";
echo "<!-- / Google Analytics by Yoast -->\n";
echo "<script type='text/javascript' src='http://coinlaundry-rapport.com/wp-includes/js/jquery/jquery.js?ver=1.11.3'></script>\n";
echo "<script type='text/javascript' src='http://coinlaundry-rapport.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.2.1'></script>\n";
echo "<link rel=\"EditURI\" type=\"application/rsd+xml\" title=\"RSD\" href=\"http://coinlaundry-rapport.com/xmlrpc.php?rsd\" />\n";
echo "<link rel=\"wlwmanifest\" type=\"application/wlwmanifest+xml\" href=\"http://coinlaundry-rapport.com/wp-includes/wlwmanifest.xml\" />\n";
echo "<meta name=\"generator\" content=\"WordPress 4.3.23\" />\n";
echo "\n";
echo "<!--[if lt IE 9]>\n";
echo "<script src=\"http://coinlaundry-rapport.com/wp-content/themes/coinlaundry-rapport.com2/js/html5shiv.js\"></script>\n";
echo "<![endif]-->\n";
echo "<!--[if (gte IE 6)&(lte IE 8)]>\n";
echo "	<script type=\"text/javascript\" src=\"http://coinlaundry-rapport.com/wp-content/themes/coinlaundry-rapport.com2/js/selectivizr.js\"></script>\n";
echo "<![endif]-->\n";
echo "\n";
echo "<!--[if lt IE 9]>\n";
echo "<script src=\"http://coinlaundry-rapport.com/wp-content/themes/coinlaundry-rapport.com2/js/respond.min.js\"></script>\n";
echo "<![endif]-->\n";
echo "\n";
echo "\n";
echo "<!--[if lt IE 9]>\n";
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"http://coinlaundry-rapport.com/wp-content/themes/coinlaundry-rapport.com2/css/ie.css\" />\n";
echo "<![endif]-->\n";
echo "\n";
echo "<!--<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js\"></script>-->\n";
echo "\n";
echo "<script src=\"http://coinlaundry-rapport.com/wp-content/themes/coinlaundry-rapport.com2/js/spot_smoothscroll.js\"></script>\n";
echo "<script src=\"http://coinlaundry-rapport.com/wp-content/themes/coinlaundry-rapport.com2/js/heightLine.js\"></script>\n";
echo "\n";
echo "<!--Vegas-->\n";
echo "<script src=\"jquery-2.1.3.min.js\"></script>\n";
echo "<script src=\"vegas.js\"></script>\n";
echo "\n";
echo "<!--font-awesome-->\n";
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"http://coinlaundry-rapport.com/wp-content/themes/coinlaundry-rapport.com2/font-awesome/css/font-awesome.min.css\">\n";
echo "\n";
echo "<script src=\"http://coinlaundry-rapport.com/wp-content/themes/coinlaundry-rapport.com2/js/case_toggle_img.js\"></script>\n";
echo "\n";
echo "\n";
echo "\n";
echo "<script>\n";
echo "  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n";
echo "  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n";
echo "  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n";
echo "  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');\n";
echo "\n";
echo "  ga('create', 'UA-436585-23', 'auto');\n";
echo "  ga('send', 'pageview');\n";
echo "\n";
echo "</script>\n";
echo "\n";
echo "</head>\n";
echo "\n";
echo "<body>\n";
echo "\n";
echo "<div id=\"header\">\n";
echo "\n";
echo "	<!--SP用ヘッダー-->\n";
echo "\n";
echo "	<!--//SP用ヘッダー-->\n";
echo "\n";
echo "	<!--PC用ヘッダー-->\n";
echo "	<div class=\"row hidden-xs hidden-sm\" style=\"margin-left: 2%; margin-right: 0;height: 600px;\">\n";
echo "		<div class=\"col-xs-4\">\n";
echo "			<a href=\"https://toshipy.github.io/coinlaundry/\">\n";
echo "				<h1>\n";
echo "					<img src=\"rainbow2.png\" alt=\"御嵩町のコインランドリー\" class=\"img-responsive header_logo m_over\"/>\n";
echo "				</h1>\n";
echo "			</a>\n";
echo "		</div>\n";
echo "		<div class=\"col-xs-8\">\n";
echo "			<ul class=\"ul_pc_header_menu\">\n";
echo "				<li>\n";
echo "	<a href=\"https://toshipy.github.io/coinlaundry/\">\n";
echo "		Home<br>\n";
echo "		<span style=\"font-size:70%;\">ホーム</span>\n";
echo "	</a>\n";
echo "</li>\n";
echo "<li>\n";
echo "	<a href=\"https://toshipy.github.io/coinlaundry-access/\">\n";
echo "		Access<br>\n";
echo "		<span style=\"font-size:70%;\">アクセス</span>\n";
echo "	</a>\n";
echo "</li>\n";
echo "\n";
echo "<li>\n";
echo "	<a href=\"https://toshipy.github.io/coinlaundry/#washable2\">\n";
echo "		Washable<br>\n";
echo "		<span style=\"font-size:70%;\">洗えるもの</span>\n";
echo "	</a>\n";
echo "</li>\n";
echo "<li>\n";
echo "	<a href=\"https://toshipy.github.io/coinlaundry/#price\">\n";
echo "		Price<br>\n";
echo "		<span style=\"font-size:70%;\">料金</span>\n";
echo "	</a>\n";
echo "</li>\n";
echo "<li>\n";
echo "	<a href=\"https://toshipy.github.io/coinlaundry/#interior\">\n";
echo "		Layout<br>\n";
echo "		<span style=\"font-size:70%;\">レイアウト</span>\n";
echo "	</a>\n";
echo "</li>			</ul>\n";
echo "						<img src=\"Laundry.jpg\" alt=\"\" class=\"img-responsive mainv_copy\"/ style=\"height:0;\">\n";
echo "			<p class=\"catch_copy\">お湯で洗濯できるコインランドリー</p>\n";
echo "			<p class=\"catch_text\">\n";
echo "				清潔感ある店内<br->\n";
echo "				電解水で除菌効果抜群！<br>\n";
echo "        選べる洗濯機サイズ！<br>\n";
echo "			</p>\n";
echo "			<p class=\"access_btn\" class=\"img_center\"><a href=\"#\" class=\"m_over\">アクセス</a></p>\n";
echo "											</div>\n";
echo "	</div>\n";
echo "	<!--//PC用ヘッダー-->\n";
echo "\n";
echo "\n";
echo "\n";
echo "\n";
echo "\n";
echo "<!--Washable-->\n";
echo "<div class=\"wrapper contents_wrapper_odd\" id=\"washable2\">\n";
echo "	<div class=\"inner\">\n";
echo "		<h2 style=\"\n";
echo "    margin-top: 40px;\n";
echo "    margin-bottom: 40px;\n";
echo "\">\n";
echo "			<img src=\"Washable2.png\" alt=\"洗えるもの\" class=\"img-responsive\">\n";
echo "			<span>洗えるもの</span>\n";
echo "		</h2>\n";
echo "\n";
echo "<div class=\"row\">\n";
echo "	<div class=\"col-xs-12 col-md-9 col-md-offset-3\" style =\"margin-left:0px;\">\n";
echo "		<p><strong>\n";
echo "					洗濯物を入れる前にボタンを押すと２分間ドラムを洗浄しますので、常に清潔で安心です。<br>\n";
echo "				</strong>\n";
echo "		</p>\n";
echo "	</div>\n";
echo "</div>\n";
echo "\n";
echo "<div class=\"row\">\n";
echo "	<div class=\"col-xs-12 col-md-4\">\n";
echo "		<div class=\"wash_cell\">\n";
echo "<h3><img src=\"Washable.png\" alt=\"洗えるもの\" class=\"img-responsive\"></h3>\n";
echo "<ul>\n";
echo "衣類\n";
echo "<li>一般衣類</li>\n";
echo "<li>ダウンジャケット（ポリウレタンは×）</li>\n";
echo "</ul>\n";
echo "<ul>\n";
echo "寝具\n";
echo "<li>毛布</li>\n";
echo "<li>羽毛布団</li>\n";
echo "<li>夏掛け布団</li>\n";
echo "<li>ベッドカバー</li>\n";
echo "<li>シーツ</li>\n";
echo "<li>布団カバー</li>\n";
echo "<li>タオルケット</li>\n";
echo "</ul>\n";
echo "<ul>\n";
echo "インテリア\n";
echo "<li>カーテン</li>\n";
echo "<li>カーペット</li>\n";
echo "<li>こたつ布団</li>\n";
echo "<li>ぬいぐるみ）</li>\n";
echo "</ul>\n";
echo "		</div>\n";
echo "	</div>\n";
echo "\n";
echo "	<div class=\"col-xs-12 col-md-4\">\n";
echo "		<div class=\"wash_cell\">\n";
echo "<h3><img src=\"Cannotwash.png\" alt=\"洗えないもの\" class=\"img-responsive\"></h3>\n";
echo "<ul>\n";
echo "衣類\n";
echo "<li>ウール・シルク製の衣類、靴</li>\n";
echo "</ul>\n";
echo "<ul>\n";
echo "寝具\n";
echo "<li>真綿布団</li>\n";
echo "<li>羊毛布団</li>\n";
echo "</ul>\n";
echo "<ul>\n";
echo "インテリア\n";
echo "<li>座布団・クッション</li>\n";
echo "</ul>\n";
echo "<hr>\n";
echo "<p>公衆衛生上のお願い<br />\n";
echo "他のお客様のご迷惑となりますので、オムツやペット用品・車や屋外で使われたマット・油汚れのひどいもの等のご利用はお断り致します。\n";
echo "</p>\n";
echo "		</div>\n";
echo "	</div>\n";
echo "\n";
echo "	<div class=\"col-xs-12 col-md-4\">\n";
echo "		<div class=\"washable_caution\">\n";
echo "\n";
echo "		</div>\n";
echo "	</div>\n";
echo "\n";
echo "</div>\n";
echo "\n";
echo "		<div class=\"row\">\n";
echo "			<div class=\"col-xs-12 col-md-9\">\n";
echo "				<p class=\"p_wash \">\n";
echo "					※当店はセルフ方式のコインランドリーです。<br />\n";
echo "					※紛失・盗難・色落ちや縮み等のトラブルにつきましては、一切責任を負いかねます。<br />\n";
echo "          お洗濯表示やご注意をよくご確認の上、ご利用下さい。</br>\n";
echo "				</p>\n";
echo "			</div>\n";
echo "		</div>\n";
echo "\n";
echo "	</div>\n";
echo "</div>\n";
echo "<!--//Washable-->\n";
echo "\n";
echo "\n";
echo "\n";
echo "<!--Price List-->\n";
echo "<div class=\"wrapper contents_wrapper_even\" id=\"price\">\n";
echo "	<div class=\"inner\">\n";
echo "		<h2 style=\"\n";
echo "    margin-top: 40px;\n";
echo "    margin-bottom: 40px;\n";
echo "\">\n";
echo "			<img src=\"pricelist.png\" alt=\"料金表\" class=\"img-responsive\">\n";
echo "			<span>料金表</span>\n";
echo "		</h2>\n";
echo "\n";
echo "		<div class=\"row\">\n";
echo "			<div class=\"col-xs-12 col-md-9 col-md-offset-3\">\n";
echo "				<p><strong>乾燥機は100円からご利用頂けます。</strong></p>\n";
echo "			</div>\n";
echo "		</div>\n";
echo "\n";
echo "		<table class=\"tbl_price\" summary=\"コインランドリー料金表\">\n";
echo "		  <tbody>\n";
echo "		    <tr>\n";
echo "          <!--<th scope=\"\"></th>\n";
echo "この属性を指定することで、それがどのデータに対する見出しなのかを明確に示すことができます。 ... そのセルが、縦列に対する見出しであることを示します。 rowgroup … そのセルが、行グループ（ thead 、 tfoot 、 tbody ）に対する見出しであることを示します。-->\n";
echo "		      <th scope=\"col\">&nbsp;</th>\n";
echo "  <!--row： 同じ行の見出しセルであることを示す。\n";
echo "col： 同じ列の見出しセルであることを示す。-->\n";
echo "		      <th scope=\"col\" class=\"even\">容量</th>\n";
echo "		      <th scope=\"col\" class=\"odd\">時間</th>\n";
echo "		      <th scope=\"col\" class=\"even\">料金</th>\n";
echo "          <th scope=\"col\" class=\"odd\">台数</th>\n";
echo "		    </tr>\n";
echo "		    <tr>\n";
echo "		      <th rowspan=\"3\" scope=\"row\">洗濯のみ</th>\n";
echo "		      <td class=\"even\">12kg</td>\n";
echo "		      <td class=\"odd\">30分</td>\n";
echo "		      <td class=\"even\">500円</td>\n";
echo "          <td class=\"odd\">1台</td>\n";
echo "\n";
echo "		    </tr>\n";
echo "		    <tr>\n";
echo "		      <td class=\"even\">17kg</td>\n";
echo "		      <td class=\"odd\">30分</td>\n";
echo "		      <td class=\"even\">700円</td>\n";
echo "          <td class=\"odd\">1台</td>\n";
echo "		    </tr>\n";
echo "        <tr>\n";
echo "          <td class=\"even\">22kg</td>\n";
echo "          <td class=\"odd\">30分</td>\n";
echo "          <td class=\"even\">1000円</td>\n";
echo "          <td class=\"odd\">1台</td>\n";
echo "        </tr>\n";
echo "\n";
echo "\n";
echo "		    <tr>\n";
echo "		      <th rowspan=\"2\" scope=\"row\">乾燥のみ</th>\n";
echo "		      <td class=\"even\">13kg</td>\n";
echo "		      <td class=\"odd\">9分</td>\n";
echo "		      <td class=\"even\">100円</td>\n";
echo "          <td class=\"odd\">5台</td>\n";
echo "		    </tr>\n";
echo "		    <tr>\n";
echo "		      <td class=\"even\">25kg</td>\n";
echo "		      <td class=\"odd\">7分</td>\n";
echo "		      <td class=\"even\">100円</td>\n";
echo "          <td class=\"odd\">2台</td>\n";
echo "		    </tr>\n";
echo "\n";
echo "\n";
echo "\n";
echo "		  </tbody>\n";
echo "		</table>\n";
echo "\n";
echo "	</div>\n";
echo "</div>\n";
echo "<!--//Price List-->\n";
echo "\n";
echo "\n";
echo "\n";
echo "<!--Interior-->\n";
echo "<div class=\"wrapper contents_wrapper_odd\" id=\"interior\">\n";
echo "	<div class=\"inner\">\n";
echo "		<h2 style=\"\n";
echo "    margin-top: 40px;\n";
echo "    margin-bottom: 40px;\n";
echo "\">\n";
echo "			<img src=\"layout.png\" alt=\"レイアウト\" class=\"img-responsive\">\n";
echo "			<span>店内情報</span>\n";
echo "		</h2>\n";
echo "\n";
echo "		<div class=\"row\">\n";
echo "			<div class=\"col-xs-12 col-md-6\">\n";
echo "				<img src=\"layout2.png\" alt=\"Laundry area\" class=\"m-b-20\">\n";
echo "\n";
echo "\n";
echo "					<div class=\"col-xs-12 col-md-9\">\n";
echo "						<p class=\"t_first\"><strong>防犯カメラ設置</strong></p>\n";
echo "						<p><strong>営業時間内call at:090-5877-6773</strong></p>\n";
echo "            <!--。<strong>～</strong>で囲んだテキストを強調し、Internet ExplorerやNetscape Navigatorなどのブラウザでは太字で表示されます-->\n";
echo "					</div>\n";
echo "				</div>\n";
echo "			</div>\n";
echo "			<div class=\"col-xs-12 col-md-6\" style=\"float:right; width:50%;\">\n";
echo "				<table class=\"tbl_interior m-b-30\" summary=\"洗濯乾燥機（小型）スペック\">\n";
echo "				  <tbody>\n";
echo "				    <tr>\n";
echo "				      <th scope=\"col\" class=\"tbl_blue\">1.</th>\n";
echo "				      <th colspan=\"3\" scope=\"col\">洗濯機×3台</th>\n";
echo "				    </tr>\n";
echo "				    <tr>\n";
echo "				      <td class=\"td_blank\">&nbsp;</td>\n";
echo "				      <td>12kg</td>\n";
echo "				      <td>洗濯のみ</td>\n";
echo "\n";
echo "				    </tr>\n";
echo "				    <tr>\n";
echo "				      <td class=\"td_blank\">&nbsp;</td>\n";
echo "				      <td>17kg</td>\n";
echo "				      <td>洗濯のみ</td>\n";
echo "				      <td>&nbsp;</td>\n";
echo "				    </tr>\n";
echo "				  </tbody>\n";
echo "				</table>\n";
echo "				<table class=\"tbl_interior m-b-30\" summary=\"洗濯乾燥機（中型）スペック\">\n";
echo "				  <tbody>\n";
echo "				    <tr>\n";
echo "				      <th scope=\"col\" class=\"tbl_blue\">2.</th>\n";
echo "				      <th colspan=\"3\" scope=\"col\">乾燥機×7台</th>\n";
echo "				    </tr>\n";
echo "				    <tr>\n";
echo "				      <td class=\"td_blank\">&nbsp;</td>\n";
echo "				      <td>13kg</td>\n";
echo "				      <td>乾燥のみ</td>\n";
echo "\n";
echo "				    </tr>\n";
echo "				    <tr>\n";
echo "				      <td class=\"td_blank\">&nbsp;</td>\n";
echo "				      <td>25kg</td>\n";
echo "				      <td>乾燥のみ</td>\n";
echo "				      <td>&nbsp;</td>\n";
echo "				    </tr>\n";
echo "				  </tbody>\n";
echo "				</table>\n";
echo "\n";
echo "			</div>\n";
echo "		</div>\n";
echo "\n";
echo "	</div>\n";
echo "</div>\n";
echo "\n";
echo "\n";
echo "\n";
echo "<!--//Interior-->\n";
echo "\n";
echo "\n";
echo "  <div class=\"main\">\n";
echo "    <div class=\"contact-form\">\n";
echo "      <div class=\"form-title\">お問い合わせ</div>\n";
echo "      <form method=\"post\" action=\"sent.php\">\n";
echo "        <div class=\"form-item\">名前</div>\n";
echo "        <input type=\"text\" name=\"name\">\n";
echo "\n";
echo "\n";
echo "        <div class=\"form-item\">お問い合わせの種類</div>\n";
echo "        <?php\n";
echo "          $types = array('Progateに関するお問い合わせ', 'Progateに対する意見', '採用に関するお問い合わせ', '取材・メディア関連のお問い合わせ', '料金に関するお問い合わせ', 'その他');\n";
echo "         ?>\n";
echo "        <!-- この下にselectタグを書いていきましょう -->\n";
echo "        <select name = \"category\">\n";
echo "          <option value =\"未選択\">選択してください</option>\n";
echo "          <?php\n";
echo "                foreach ($types as $type) {\n";
echo "      echo \"<option value='{$type}'>{$type}</option>\";}\n";
echo "          ?>\n";
echo "        </select>\n";
echo "\n";
echo "        <div class=\"form-item\">内容</div>\n";
echo "        <textarea name=\"body\"></textarea>\n";
echo "\n";
echo "        <input type=\"submit\" value=\"送信\">\n";
echo "      </form>\n";
echo "    </div>\n";
echo "  </div>\n";
echo "\n";
echo "  <div class=\"footer\">\n";
echo "\n";
echo "    <div class=\"like-box\">\n";
echo "      <div class=\"btn-wrapper\">\n";
echo "          <a href=\"https://twitter.com/Parkalleyoop\" class=\"btn twitter\"><span class=\"fa fa-twitter\"></span>TwitterからDMでお問い合わせ</a>\n";
echo "        </div>\n";
echo "        </div>\n";
echo "  </div>\n";
echo "\n";
echo "\n";
echo "\n";
echo "\n";
echo "<div class=\"footer_wrapper\">\n";
echo "<p id=\"page-top\" class=\"img_center\"><a href=\"#top\" class=\"m_over\"><i class=\"fa fa-chevron-up\"></i></a></p>\n";
echo "    <p class=\"text-center\" style=\"margin-top: 12px;\"><a href=\"#top\" class=\"m_over\"><strong>Page Top</strong></a></p>\n";
echo "	<div class=\"container footer_inner\" style=\"margin-bottom:10px;\">\n";
echo "        <div class=\"row\">\n";
echo "            <div class=\"col-xs-12 col-md-9 heightLine-sns\">\n";
echo "        		<a href=\"#\">\n";
echo "        			<img src=\"rainbow2.png\" alt=\"御嵩町のコインランドリーレインボー\" class=\"footer_logo m_over img-responsive\"/>\n";
echo "        		</a>\n";
echo "        		<p>コインランドリーレインボー 可児郡御嵩町1146-2　営業時間：朝６時〜夜１１時まで　定休日：年中無休</p>\n";
echo "            </div>\n";
echo "            <div class=\"col-xs-12 col-md-3\" style=\"display: table;\">\n";
echo "            <div id=\"sns_box\" class=\"heightLine-sns\">\n";
echo "                <p id=\"facebook_btn\"><a href=\"#\" class=\"m_over\" target=\"_blank\">f</a></p>\n";
echo "\n";
echo "                <div class=\"clear\"></div>\n";
echo "            </div>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "	</div>\n";
echo "</div>\n";
echo "<div class=\"f_copyright\">\n";
echo "<p class=\"text-center\">&copy; <a href=\"#\">RAINBOW</a> ALL RIGHTS RESERVED.</p>\n";
echo "</div>\n";
echo "\n";
echo "\n";
echo "</body>\n";
echo "</html>\n";
echo "";
?>
